### ISSUE TITLE
Call to undefined function RefRing\MoneroRpcPhp\Model\bcdiv()

### ISSUE THREAD

**Issue by jasonestewart** [refring/monero-rpc-php#14]
#0 [my project]/vendor/refring/monero-rpc-php/src/Model/Amount.php(24): RefRing\\MoneroRpcPhp\\Model\\Amount->toDenomination()
#1[my project]/MoneroPaymentService.php(184):` RefRing\\MoneroRpcPhp\\Model\\Amount->toXmr()

    private function toDenomination(int $denomination): string
    {
        return bcdiv($this->amount, (string) $denomination, 12);
    }

**Comment by jasonestewart** [comment]
This is happening because bcmath php extension was not loaded on my system - is there a way to require it in the composer.json?

**Comment by refring** [comment]
Hi @jasonestewart, thank you for bringing this to our attention.

I've updated the project to include `ext-bcmath` as a Composer dependency. This ensures that Composer will notify you if the `ext-bcmath` extension is not present on your system. 

It's important to note that Composer does not automatically install PHP extensions. Therefore, you'll need to install `ext-bcmath` manually.

Please feel free to reach out if you encounter any further issues or have questions, I'll close the issue for now.
